version: 2.1
jobs:
  build:

    docker:
      - image: circleci/python:3.6.7

    steps:
      - checkout

      - run:
          name: create virtualenv
          command: |
            python3 -m venv venv
            . venv/bin/activate

      - run:
          name: install torchcast
          command: |
            . venv/bin/activate
            pip install .[tests]

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python3 -m unittest